### ISSUE TITLE
Changed Variable Count Distance

### ISSUE THREAD

**Issue by psieg** [psieg/babelsberg-js#15]
#12 Use the number of changed variables as a measure of awesomeness.

**Comment by j4yk** [comment]
I merged the current development branch into the one for this issue. I would like to write a test for this but I do not think it is ready or fully specified yet. We do want to have a choice whether to select by time or the number of changed variables, correct? Currently it looks like the selection always considers time first.

**Comment by LRueckert** [comment]
This was not finished and i stopped working on it when we realized that the tests were failing and i was planning on manually merging it when we merged the capabilities branch into dev.

**Comment by j4yk** [comment]
Resolved by #24
